### PR TITLE
chart update

### PR DESCRIPTION
**Pull request by tigredonorte**
chart update on data change fixed

### CODE REVIEW

**Comment by Pauan** [comment]
Hi @tigredonorte,

I don't understand what the purpose of these changes is. What problem is it trying to solve?

**Comment by tigredonorte** [comment]
First change is: in old code, when you update chart data, the chart not redraw. 
Second: in old code has some global funcions. This approach can broke the code when use other dependencies. I fixed this, moving all global functions to inside directive. Maybe, an better approach is transform this methods in some service. But i don't do that now.

**Comment by Pauan** [comment]
@tigredonorte None of the functions are global. Angular2 uses TypeScript, which uses ES2015 modules. That means that all of the variables are local, not global.

Please try to minimize the amount of changes that you make, it is currently very difficult for me to review the changes.

**Comment by ryzy** [comment]
Hi,

Is this change still valid since we now deprecating `amcharts.directive` in favour of `AmChartsService`?

**Pull request closed without merging**
